language: python
dist: xenial
jobs:
  include:
    - name: 'docs'
      python: '3.7'
      script:
        - sphinx-build -E -b html docs dist/docs
        - sphinx-build -b linkcheck docs dist/docs

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

before_install:
  - python -m pip install --upgrade pip
  # Get the program and testing requirements
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt
  # set up data directory
  - mkdir /home/travis/build/pysatData
  - python -c "import pysat; pysat.params['data_dirs'] = '/home/travis/build/pysatData'"

install:
  - python setup.py install
